### ISSUE TITLE
Develop in github

### ISSUE THREAD

**Issue by tonymadbrain** [shemminger/iproute2#11]
I think will be better if iproute2 will developing in github, then a lot of peoples be able to help with issues and patches. We want to improve ss utility from iproute2, but send patches via email is not the way, it is so 199x.

**Comment by jadjay** [comment]
+2500000 🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟...

Le 22 septembre 2016 10:55:25 CEST, Antony <notifications@github.com> a écrit :
>I think will be better if iproute2 will developing in github, then a
>lot of peoples be able to help with issues and patches. We want to
>improve ss utility from iproute2, but send patches via email is not the
>way, it is so 199x.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/shemminger/iproute2/issues/11

-- 
Jérôme Avond - aka jadjay 
Agitateur chez Alolise depuis avril 2005 
... et président depuis 2014 

mail/xmpp  : jerome.avond@alolise.org 
mobile  : 0661469785

 Alolise est membre du collectif C.H.A.T.O.N.S

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by shemminger** [comment]
On Thu, 22 Sep 2016 01:55:25 -0700
Antony <notifications@github.com> wrote:

> I think will be better if iproute2 will developing in github, then a lot of peoples be able to help with issues and patches. We want to improve ss utility from iproute2, but send patches via email is not the way, it is so 199x.
> 

No. kernel.org and mailing list corresponds with the existing kernel network development
process.

**Comment by hjalves** [comment]
Hi! Is there any discussion forum / IRC channel for iproute2? And the [main information page link is broken too](http://www.linuxfoundation.org/collaborate/workgroups/networking/iproute2).

**Comment by shemminger** [comment]
On Thu, 12 Oct 2017 23:56:30 -0700
Humberto Alves <notifications@github.com> wrote:

> Hi! Is there any discussion forum / IRC channel for iproute2? And the [main information page link is broken too](http://www.linuxfoundation.org/collaborate/workgroups/networking/iproute2).
> 

Use mailing list netdev@vger.kernel.org

**Comment by shemminger** [comment]
iproute2 is developed upstream on kernel.org
