### ISSUE TITLE
'ip rule show' and 'add' is showing error 

### ISSUE THREAD

**Issue by gksalil** [shemminger/iproute2#13]
Hello

 I am trying `ip rule <add | show> command in my custom linux server. This gives error as below

> ~ # ip rule show
> RTNETLINK answers: Address family not supported by protocol
> Dump terminated
> ~ # ip rule add
> RTNETLINK answers: Address family not supported by protocol

How do I get rid of this issue.

> ~ # ip -V
> ip utility, iproute2-ss170905

kernel version is 4.13 

Thanks in advance
~S

**Comment by gksalil** [comment]
Hello

  Any help in this regard would be really appreciated

~S

**Comment by stigt** [comment]
Have you verified that your kernel has policy based routing enabled?

**Comment by gksalil** [comment]
Thanks for the pointers. Could you please help me to check if it is enabled or not. I will check it and update this thread.

Thanks
~S

**Comment by shemminger** [comment]
Look at your kernel configuration. Most distributions put it in
/boot/config-$(uname -r)

**Comment by gksalil** [comment]
In my server machine I cannot see this file. 
Can I see this information in kernel build directory ( as my server build kernel 4.13 and get the required from the build ) ? If so where should I look at ?

~S

**Comment by shemminger** [comment]
On Tue, 10 Oct 2017 23:56:05 +0000 (UTC)
gksalil <notifications@github.com> wrote:

> In my server machine I cannot see this file. 
> Can I see this information in kernel build directory ( as my server build kernel 4.13 and get the required from the build ) ? If so where should I look at ?
> 
> ~S
> 

Look in /boot directory.  The kernel is vmlinux followed by version number.
The config file is usually stored there with config followed by version number.
Of course if you want to change the config, you have to do a full kernel build from source.

**Comment by gksalil** [comment]
In my /boot directory the following is the contents
~ # ls -l /boot
total 10820
-rw-rw-r-- 1 root root 8597968 Oct 10 03:52 bzImage
-rwxr-xr-x 1 root root  123648 Sep 21 03:49 memtest.bin
-rw-rw-r-- 1 root root 2322932 Oct 10 03:52 System.map

I can boot kernel from source. What parameter should I specify while building the kernel to get this support

Thanks
~S

**Comment by shemminger** [comment]
On Thu, 12 Oct 2017 02:00:44 +0000 (UTC)
gksalil <notifications@github.com> wrote:

> In my /boot directory the following is the contents
> ~ # ls -l /boot
> total 10820
> -rw-rw-r-- 1 root root 8597968 Oct 10 03:52 bzImage
> -rwxr-xr-x 1 root root  123648 Sep 21 03:49 memtest.bin
> -rw-rw-r-- 1 root root 2322932 Oct 10 03:52 System.map
> 
> I can boot kernel from source. What parameter should I specify while building the kernel to get this support
> 
> Thanks
> ~S
> 
Sigh, it is some old embedded system.

$ grep MULTIPLE_TABLES .config
CONFIG_IP_MULTIPLE_TABLES=y
# CONFIG_IP_MROUTE_MULTIPLE_TABLES is not set
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_IPV6_MROUTE_MULTIPLE_TABLES=y


You may want to enable IP_MROUTE_MULTIPLE_TABLES if doing multicast routing.

**Comment by gksalil** [comment]
The following is the grep output in kernel compilation directory.

~# grep MULTIPLE .config
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_IP_MULTIPLE_TABLES=y

**Comment by gksalil** [comment]
Any help on this would be highly appreciated - I am kind of held up on this.

**Comment by shemminger** [comment]
On Mon, 23 Oct 2017 10:32:30 +0000 (UTC)
gksalil <notifications@github.com> wrote:

> Any help on this would be highly appreciated - I am kind of held up on this.
> 

All discussions and bug reports should be directed to the mailing list.
Like people suggested, look at the kernel config.

**Comment by gksalil** [comment]
This issue is resolved - that was actually build system issue - the above said kernel parameters were not getting compiled during my kernel compilation because of some other scripting issues.
Thanks for the help.
