### ISSUE TITLE
Need some help on my routing problem

### ISSUE THREAD

**Issue by gksalil** [shemminger/iproute2#14]
I am trying to configure sslh in my machine in transparent proxy  mode for which I have done some iptable entries and added some routes and rules. 

>  What I am trying to do is keep sslh open in 443 port and redirect requests to 445 port of apache.

But what I observed while doing tcpdump analysis is - 

request from my browser client is coming to **eth0**  
response from the system is being directed to **lo** interface

Because of which the browser is not getting the response. How do I solve this issue ?

Below are the rules I added to the system

> 
> iptables -t mangle -F
> iptables -t mangle -X SSLH
> iptables -t mangle -N SSLH
> iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 443 --jump SSLH
> iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
> iptables -t mangle -A SSLH --jump ACCEPT
> ip rule add fwmark 0x1 lookup 100
> ip route add local 0.0.0.0/0 dev lo table 100

> ~ \# ip rule show
> 0:	from all lookup local 
> 32764:	from all fwmark 0x1 lookup 100 
> 32765:	from all fwmark 0x1 lookup 100 
> 32766:	from all lookup main 
> 32767:	from all lookup default

> ~ \# ip route show
> default via 10.50.156.1 dev eth0 
> 10.50.156.0/22 dev eth0 proto kernel scope link src 10.50.157.85 

Below command shows the packets are being sent lo interface
> tcpdump tcp and not port ssh and host 10.65.60.244  -i lo -n

Below command shows the packets are coming from client browser
> tcpdump tcp and not port ssh and host 10.65.60.244  -i eth0 -n

If any more information is required, I can provide them
S

**Comment by shemminger** [comment]
Please don't ask questions to me directly.
Better to discuss on mailing lists.
For general networking netdev@vger.kernel.org
For netfilter use netfilter@vger.kernel.org

**Comment by gksalil** [comment]
sure - thanks for pointing this.
I think the message I have posted is not for this list . it was more of an administration kind of question. Sorry about this.
