### ISSUE TITLE
Is iprout2 removed from Linux kernel git?

### ISSUE THREAD

**Issue by Hellseher** [shemminger/iproute2#15]
Hi,

Just found that there is no any trace of **iproute2** source or wiki page in Linux git or Linuxfoundation.

Dead links

- https://wiki.linuxfoundation.org/networking/iproute2
- https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/

Where can I find up-to-date sources?

**Comment by shemminger** [comment]
The iproute2 upstream repo is now at:
  https://git.kernel.org/pub/scm/network/iproute2/iproute2.git
and
  https://git.kernel.org/pub/scm/network/iproute2/iproute2-next.git

The old locations still exist and are links. The links aren't visible in the GUI.

**Comment by shemminger** [comment]
see above
