### ISSUE TITLE
Kernel-panic after start tc class add dev eth0 parent 20:7 classid 20:1 htb rate 200kbit ceil 10000kbit prio 0

### ISSUE THREAD

**Issue by Roland-F** [shemminger/iproute2#16]
When i made the following commands with kernel 4.14.15 and iproute2 4.14.1 i will get an kernel-panic.
The commands will be:
tc qdisc add dev eth0 root handle 20: htb default 4 r2q 1
tc class add dev eth0 parent 20: classid 20:7 htb rate 10000kbit
tc qdisc add dev eth0 parent 20:7 sfq perturb 10
tc class add dev eth0 parent 20:7 classid 20:1 htb rate 200kbit ceil 10000kbit prio 0

After the last command i will get an:
BUG: scheduling while atomic: tc/4421/0x00000202

Anyone who can check this situation?
Will this be solved by kernel-line 4.14 also or only with 4.15?

**Comment by zhangsju** [comment]
i got the same issue here, anyone who can check this?

**Comment by zhangsju** [comment]
@Roland-F 
i got the same issue here, have you ever found any solution? thinks.

**Comment by Roland-F** [comment]
Hello,
only as information:
The page from “shemminger” is not the official page from iproute2 (I was also first there wrong).
There is an mailing-list of “netdev”, where i have also given the information.
Here i have an directly replay got from the maintainer of the linux-kernel (Special for network).
They have found the bug and be at the work for solving this.
Hope that this is be solved together with kernel 1.15.3 and 1.14.19.
You can search here in the kernel-changelog for an patch to: 

net_sched: get rid of rcu_barrier() in tcf_block_put_ext()


Best regards,
Roland

**Comment by Roland-F** [comment]
Hello again,
with the patch on: https://patchwork.ozlabs.org/patch/844372/
The kernel-line 4.15 (Used actually by 4.15.2) the fault is gone.
But as there be a lot of changes between the kernel-line 4.14 and 4.15
the patch in the actually form will not can be used by the kernel-line 4.14

Best regards,
Roland

**Comment by zhangsju** [comment]
thanks, looks like i need to switch to the latest kernel 4.15.2.

**Comment by Roland-F** [comment]
Hello,
you have to switch at the kernel 4.15.3, as there is the function working. (Will come !!)
If the function come back with the 4.14.19 or later is not know from me actually, as 
i must wait also for the work from others.

**Comment by shemminger** [comment]
read earlier issue. this project does not use github for project management
