### ISSUE TITLE
Problem with setting up FOU tunnel through NAT

### ISSUE THREAD

**Issue by kpeletidis** [shemminger/iproute2#17]
I am having trouble with a particular case of setting up a fou tunnel and I would really appreciate your help.

I have a multihomed host behind a NAT box and I want to create a fou tunnel for each of its IP addresses.

A typical case would be something like that:

```
# ip tun
ipudp09602: ip/ip remote 135.196.22.100 local 172.31.0.140 ttl 225
ipudp00101: ip/ip remote 148.252.129.30 local 172.31.0.140 ttl 225
ipudp09604: ip/ip remote 77.247.11.249 local 172.31.0.140 ttl 225
tunl0: any/ip remote any local any ttl inherit nopmtudisc
ipudp00102: ip/ip remote 213.205.194.18 local 172.31.0.140 ttl 225
```

However, if the remote end has the same IP address with the remote end of an existing tunnel (but a different remote port)
tunnel creation fails. In this example there is already a tunnel to 135.196.22.100:32270 and I wanted to create a new tunnel to 135.196.22.100:24822 as below:

```
# ip link add name ipudp09603 mtu 1356 type ipip \
  remote 135.196.22.100 \
  local 172.31.0.140 \
  ttl 225 \
  encap fou \
     encap-sport 4500 \
     encap-dport 24822

RTNETLINK answers: File exists
```

The remote IP addresses in this case are identical because there is a NAT box in the way, but the port numbers are different.

Is there a way to have such a fou tunnel as described above? Thank you.

**Comment by shemminger** [comment]
Please direct all iproute2 questions and patches to netdev@vger.kernel.org mailing list.
Often these are kernel related, not an issue with the commands itself.

**Comment by kpeletidis** [comment]
Thank you for the prompt response and the pointer. As far as I am concerned this issue can be closed.
