### ISSUE TITLE
tc qdisc prints different probability than configure for RED

### ISSUE THREAD

**Issue by dboru** [shemminger/iproute2#19]
Hi, 
I configured RED qdisc for my interface as follows 

tc qdisc replace dev eth1 parent 4: handle 10: red  limit 100000 min 30000 max 30001 avpkt 1500  burst 21 ecn  probability 1.0 bandwidth 1000Mbit

I wanted to verify if the parameters are set correctly and did 
tc -d qdisc show dev eth1
qdisc red 10: parent 4: limit 100000b min 30000b max 30001b ecn ewma 2 probability 0.5 Scell_log 6

I set the ECN marking probability to 1.0 but tc prints 0.5, when I configure a different value than 1.0 the tc show command prints what I have configured.  
What should I do to set the RED marking probability  to 1?

**Comment by shemminger** [comment]
this is not the place where problems ar handled. this is likely a kernel issue.
Please post to netdev@vger.kernel.org
