### ISSUE TITLE
ss -H output

### ISSUE THREAD

**Issue by YoyPa** [shemminger/iproute2#20]
When using ss -Hutn4, **Netid** and **State** are sometime merged, it can be confusing when trying to pipe into awk or column.
```
#this one is wrong (see column number)
$ ss -Hutn4 | column -tN 1,2,3,4,5,6    
1            2  3  4                            5                    6
tcpESTAB     0  0  192.168.1.160:45986          54.200.178.216:443   
tcpESTAB     0  0  192.168.1.160:53854          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:45394          54.75.239.212:443    
tcpESTAB     0  0  192.168.1.160:53864          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:56492          79.125.105.113:443   
tcpESTAB     0  0  192.168.1.160:53846          151.101.112.133:443  
tcpSYN-SENT  0  1  192.168.1.160%enp61s0:36590  138.201.81.199:80    
tcpESTAB     0  0  192.168.1.160:53870          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:40572          46.43.9.146:443      
tcpESTAB     0  0  192.168.1.160:53862          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:53842          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:53866          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:41408          173.194.76.108:993   
tcpESTAB     0  0  192.168.1.160:53860          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:45016          74.125.71.109:993    
tcpESTAB     0  0  192.168.1.160:53868          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:53844          151.101.112.133:443  
tcpESTAB     0  0  192.168.1.160:53858          151.101.112.133:443  

#this one is ok
$ ss -Hutn4 | column -tN 1,2,3,4,5,6
1    2      3  4  5                    6
tcp  ESTAB  0  0  192.168.1.160:45986  54.200.178.216:443
tcp  ESTAB  0  0  192.168.1.160:53854  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:45394  54.75.239.212:443
tcp  ESTAB  0  0  192.168.1.160:53864  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:56492  79.125.105.113:443
tcp  ESTAB  0  0  192.168.1.160:53846  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:53870  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:40572  46.43.9.146:443
tcp  ESTAB  0  0  192.168.1.160:53862  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:53842  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:53866  151.101.112.133:443
tcp  ESTAB  0  0  192.168.1.160:41408  173.194.76.108:993
tcp  ESTAB  0  0  192.168.1.160:53860  151.101.112.133:443
```
When -H is not present it's the same for **Netid** and **State** titles.
Also **Local/Peer Address** titles are a bit messy (replacing " " by "_" should fix that).
```
$ ss -utn4 | column -tN 1,2,3,4,5,6,7
1           2         3       4      5                            6                    7
NetidState  Recv-Q    Send-Q  Local  Address:Port                 Peer                 Address:Port
tcp         ESTAB     0       0      192.168.1.160:45986          54.200.178.216:443   
tcp         ESTAB     0       0      192.168.1.160:53908          151.101.112.133:443  
tcp         ESTAB     0       0      192.168.1.160:40572          46.43.9.146:443      
tcp         ESTAB     0       0      192.168.1.160:53898          151.101.112.133:443  
tcp         ESTAB     0       0      192.168.1.160:41408          173.194.76.108:993   
tcp         ESTAB     0       0      192.168.1.160:58938          192.30.253.125:443   
tcp         ESTAB     0       0      192.168.1.160:53904          151.101.112.133:443  
tcp         SYN-SENT  0       1      192.168.1.160%enp61s0:36628  138.201.81.199:80    
tcp         ESTAB     0       0      192.168.1.160:45016          74.125.71.109:993    
tcp         ESTAB     0       0      192.168.1.160:53902          151.101.112.133:443  
tcp         ESTAB     0       0      192.168.1.160:53900          151.101.112.133:443  
tcp         ESTAB     0       0      192.168.1.160:53906          151.101.112.133:443
```
-- Info --
```
Linux yo-gs 4.19.0-1-MANJARO #1 SMP PREEMPT Mon Oct 22 18:40:59 UTC 2018 x86_64 GNU/Linux
local/iproute2 4.19.0-1 (base)
```

**Comment by shemminger** [comment]
On Fri, 26 Oct 2018 07:13:51 -0700
YoyPa <notifications@github.com> wrote:

> When using ss -Hutn4, **Netid** and **State** are sometime merged, it can be confusing when trying to pipe into awk or column.
> ```
> #this one is wrong (see column number)
> $ ss -Hutn4 | column -tN 1,2,3,4,5,6    
> 1            2  3  4                            5                    6
> tcpESTAB     0  0  192.168.1.160:45986          54.200.178.216:443   
> tcpESTAB     0  0  192.168.1.160:53854          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:45394          54.75.239.212:443    
> tcpESTAB     0  0  192.168.1.160:53864          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:56492          79.125.105.113:443   
> tcpESTAB     0  0  192.168.1.160:53846          151.101.112.133:443  
> tcpSYN-SENT  0  1  192.168.1.160%enp61s0:36590  138.201.81.199:80    
> tcpESTAB     0  0  192.168.1.160:53870          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:40572          46.43.9.146:443      
> tcpESTAB     0  0  192.168.1.160:53862          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:53842          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:53866          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:41408          173.194.76.108:993   
> tcpESTAB     0  0  192.168.1.160:53860          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:45016          74.125.71.109:993    
> tcpESTAB     0  0  192.168.1.160:53868          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:53844          151.101.112.133:443  
> tcpESTAB     0  0  192.168.1.160:53858          151.101.112.133:443  
> 
> #this one is ok
> $ ss -Hutn4 | column -tN 1,2,3,4,5,6
> 1    2      3  4  5                    6
> tcp  ESTAB  0  0  192.168.1.160:45986  54.200.178.216:443
> tcp  ESTAB  0  0  192.168.1.160:53854  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:45394  54.75.239.212:443
> tcp  ESTAB  0  0  192.168.1.160:53864  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:56492  79.125.105.113:443
> tcp  ESTAB  0  0  192.168.1.160:53846  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:53870  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:40572  46.43.9.146:443
> tcp  ESTAB  0  0  192.168.1.160:53862  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:53842  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:53866  151.101.112.133:443
> tcp  ESTAB  0  0  192.168.1.160:41408  173.194.76.108:993
> tcp  ESTAB  0  0  192.168.1.160:53860  151.101.112.133:443
> ```
> When -H is not present it's also messy but only for column title (replacing " " by "_" in local&peer address should fix that).
> ```
> $ ss -utn4 | column -tN 1,2,3,4,5,6,7
> 1           2         3       4      5                            6                    7
> NetidState  Recv-Q    Send-Q  Local  Address:Port                 Peer                 Address:Port
> tcp         ESTAB     0       0      192.168.1.160:45986          54.200.178.216:443   
> tcp         ESTAB     0       0      192.168.1.160:53908          151.101.112.133:443  
> tcp         ESTAB     0       0      192.168.1.160:40572          46.43.9.146:443      
> tcp         ESTAB     0       0      192.168.1.160:53898          151.101.112.133:443  
> tcp         ESTAB     0       0      192.168.1.160:41408          173.194.76.108:993   
> tcp         ESTAB     0       0      192.168.1.160:58938          192.30.253.125:443   
> tcp         ESTAB     0       0      192.168.1.160:53904          151.101.112.133:443  
> tcp         SYN-SENT  0       1      192.168.1.160%enp61s0:36628  138.201.81.199:80    
> tcp         ESTAB     0       0      192.168.1.160:45016          74.125.71.109:993    
> tcp         ESTAB     0       0      192.168.1.160:53902          151.101.112.133:443  
> tcp         ESTAB     0       0      192.168.1.160:53900          151.101.112.133:443  
> tcp         ESTAB     0       0      192.168.1.160:53906          151.101.112.133:443
> ```
> 

Thank you for  your report. This is a community project, and we don't use github directly.
Please see if problem occurs with latest version 4.19 from kernel.org.

To report problems and send patches to netdev@vger.kernel.org mailing list.

**Comment by YoyPa** [comment]
I added the info on my first post, I was using the Archlinux.org 4.19.0-1 iproute2 package.
I just tested from the kernel.org git and it's the same.
v4.18.0-1is also behaving the same way, it's not a new "bug".

**Comment by YoyPa** [comment]
Following changes solve both issue (title and content) but waste 2 space when -H option is used
```(tcp   ESTAB instead of tcpESTAB)```
```
diff --git a/misc/ss.c b/misc/ss.c
index c8970438..5e46cc0e 100644
--- a/misc/ss.c
+++ b/misc/ss.c
@@ -144,9 +144,9 @@ static struct column columns[] = {
        { ALIGN_LEFT,   "State",                " ",    0, 0, 0 },
        { ALIGN_LEFT,   "Recv-Q",               " ",    0, 0, 0 },
        { ALIGN_LEFT,   "Send-Q",               " ",    0, 0, 0 },
-       { ALIGN_RIGHT,  "Local Address:",       " ",    0, 0, 0 },
+       { ALIGN_RIGHT,  "Local_Address:",       " ",    0, 0, 0 },
        { ALIGN_LEFT,   "Port",                 "",     0, 0, 0 },
-       { ALIGN_RIGHT,  "Peer Address:",        " ",    0, 0, 0 },
+       { ALIGN_RIGHT,  "Peer_Address:",        " ",    0, 0, 0 },
        { ALIGN_LEFT,   "Port",                 "",     0, 0, 0 },
        { ALIGN_LEFT,   "",                     "",     0, 0, 0 },
 };
@@ -1334,7 +1334,7 @@ static void sock_state_print(struct sockstat *s)
                out("`- %s", sctp_sstate_name[s->state]);
        } else {
                field_set(COL_NETID);
-               out("%s", sock_name);
+               out("%-6s", sock_name);
                field_set(COL_STATE);
                out("%s", sstate_name[s->state]);
        }
```
ouput with changes applied:
```
$ ss -utn4 | column -tN 1,2,3,4,5,6
1      2           3       4       5                            6
Netid  State       Recv-Q  Send-Q  Local_Address:Port           Peer_Address:Port
tcp    CLOSE-WAIT  1       0       192.168.1.160:38766          104.27.155.125:80
tcp    ESTAB       0       0       192.168.1.160:36806          216.58.198.206:443
tcp    ESTAB       0       0       192.168.1.160:48444          104.18.61.250:443
tcp    ESTAB       0       0       192.168.1.160:38242          64.233.167.109:993
tcp    SYN-SENT    0       1       192.168.1.160%enp61s0:39184  138.201.81.199:80
tcp    ESTAB       0       0       192.168.1.160:41490          192.30.253.112:443
tcp    ESTAB       0       0       192.168.1.160:60556          192.30.253.125:443
tcp    ESTAB       4149    0       192.168.1.160:48280          104.24.23.87:443
tcp    ESTAB       27      0       192.168.1.160:44066          104.24.22.87:443
tcp    ESTAB       0       0       192.168.1.160:52906          34.209.0.68:443
tcp    ESTAB       0       0       192.168.1.160:38696          216.58.206.238:443

$ ss -Hutn4 | column -tN 1,2,3,4,5,6
1    2           3     4  5                            6
tcp  CLOSE-WAIT  1     0  192.168.1.160:38766          104.27.155.125:80
tcp  ESTAB       0     0  192.168.1.160:36806          216.58.198.206:443
tcp  ESTAB       0     0  192.168.1.160:48444          104.18.61.250:443
tcp  ESTAB       0     0  192.168.1.160:38242          64.233.167.109:993
tcp  SYN-SENT    0     1  192.168.1.160%enp61s0:39184  138.201.81.199:80
tcp  ESTAB       0     0  192.168.1.160:41490          192.30.253.112:443
tcp  ESTAB       0     0  192.168.1.160:60556          192.30.253.125:443
tcp  ESTAB       4149  0  192.168.1.160:48280          104.24.23.87:443
tcp  ESTAB       27    0  192.168.1.160:44066          104.24.22.87:443
tcp  ESTAB       0     0  192.168.1.160:52906          34.209.0.68:443
tcp  ESTAB       0     0  192.168.1.160:38696          216.58.206.238:443
```

**Comment by shemminger** [comment]
On Fri, 26 Oct 2018 19:09:32 +0000 (UTC)
YoyPa <notifications@github.com> wrote:

> Following changes solve both issue (title and content) but waste 2 space when -H option is used
> ```(tcp   ESTAB instead of tcpESTAB)```
> ```
> diff --git a/misc/ss.c b/misc/ss.c
> index c8970438..5e46cc0e 100644
> --- a/misc/ss.c
> +++ b/misc/ss.c
> @@ -144,9 +144,9 @@ static struct column columns[] = {
>         { ALIGN_LEFT,   "State",                " ",    0, 0, 0 },
>         { ALIGN_LEFT,   "Recv-Q",               " ",    0, 0, 0 },
>         { ALIGN_LEFT,   "Send-Q",               " ",    0, 0, 0 },
> -       { ALIGN_RIGHT,  "Local Address:",       " ",    0, 0, 0 },
> +       { ALIGN_RIGHT,  "Local_Address:",       " ",    0, 0, 0 },
>         { ALIGN_LEFT,   "Port",                 "",     0, 0, 0 },
> -       { ALIGN_RIGHT,  "Peer Address:",        " ",    0, 0, 0 },
> +       { ALIGN_RIGHT,  "Peer_Address:",        " ",    0, 0, 0 },
>         { ALIGN_LEFT,   "Port",                 "",     0, 0, 0 },
>         { ALIGN_LEFT,   "",                     "",     0, 0, 0 },
>  };
> @@ -1334,7 +1334,7 @@ static void sock_state_print(struct sockstat *s)
>                 out("`- %s", sctp_sstate_name[s->state]);
>         } else {
>                 field_set(COL_NETID);
> -               out("%s", sock_name);
> +               out("%-6s", sock_name);
>                 field_set(COL_STATE);
>                 out("%s", sstate_name[s->state]);
>         }
> ```
> ouput with changes applied:
> ```
> $ ss -utn4 | column -tN 1,2,3,4,5,6
> 1      2           3       4       5                            6
> Netid  State       Recv-Q  Send-Q  Local_Address:Port           Peer_Address:Port
> tcp    CLOSE-WAIT  1       0       192.168.1.160:38766          104.27.155.125:80
> tcp    ESTAB       0       0       192.168.1.160:36806          216.58.198.206:443
> tcp    ESTAB       0       0       192.168.1.160:48444          104.18.61.250:443
> tcp    ESTAB       0       0       192.168.1.160:38242          64.233.167.109:993
> tcp    SYN-SENT    0       1       192.168.1.160%enp61s0:39184  138.201.81.199:80
> tcp    ESTAB       0       0       192.168.1.160:41490          192.30.253.112:443
> tcp    ESTAB       0       0       192.168.1.160:60556          192.30.253.125:443
> tcp    ESTAB       4149    0       192.168.1.160:48280          104.24.23.87:443
> tcp    ESTAB       27      0       192.168.1.160:44066          104.24.22.87:443
> tcp    ESTAB       0       0       192.168.1.160:52906          34.209.0.68:443
> tcp    ESTAB       0       0       192.168.1.160:38696          216.58.206.238:443
> 
> $ ss -Hutn4 | column -tN 1,2,3,4,5,6
> 1    2           3     4  5                            6
> tcp  CLOSE-WAIT  1     0  192.168.1.160:38766          104.27.155.125:80
> tcp  ESTAB       0     0  192.168.1.160:36806          216.58.198.206:443
> tcp  ESTAB       0     0  192.168.1.160:48444          104.18.61.250:443
> tcp  ESTAB       0     0  192.168.1.160:38242          64.233.167.109:993
> tcp  SYN-SENT    0     1  192.168.1.160%enp61s0:39184  138.201.81.199:80
> tcp  ESTAB       0     0  192.168.1.160:41490          192.30.253.112:443
> tcp  ESTAB       0     0  192.168.1.160:60556          192.30.253.125:443
> tcp  ESTAB       4149  0  192.168.1.160:48280          104.24.23.87:443
> tcp  ESTAB       27    0  192.168.1.160:44066          104.24.22.87:443
> tcp  ESTAB       0     0  192.168.1.160:52906          34.209.0.68:443
> tcp  ESTAB       0     0  192.168.1.160:38696          216.58.206.238:443
> ```
> 

Send patches with proper signed-off-by to netdev@vger.kernel.org

**Comment by YoyPa** [comment]
Fixed by https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=00240899ec0b0bb296ee54860802adec3be0d26e
