### ISSUE TITLE
can't see vlan details in listing

### ISSUE THREAD

**Issue by Harvie** [shemminger/iproute2#21]
I have set some parameters using ip link like this:

```bash
ip link set eth0.422 type vlan loose_binding on mvrp on gvrp on
```
But i can't verify that they were really set. I don't see current setting of **loose_binding, mvrp and gvrp** options in **ip link show** listing:

```
# ip link show type vlan
5: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
6: eth0.422@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
7: eth0.420@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
8: eth0.423@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
```
So for example if i want to make sure that GVRP is (in)active, i have to (un)set it again.

**Comment by shemminger** [comment]
On Thu, 15 Nov 2018 16:00:22 -0800
Tomas Mudrunka <notifications@github.com> wrote:

> I have set some parameters using ip link like this:
> 
> ```bash
> ip link set eth0.422 type vlan loose_binding on mvrp on gvrp on
> ```
> But i can't verify that they were really set. I don't see current setting of **loose_binding, mvrp and gvrp** options in **ip link show** listing:
> 
> ```
> # ip link show type vlan
> 5: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
>     link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
> 6: eth0.422@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
>     link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
> 7: eth0.420@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
>     link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
> 8: eth0.423@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
>     link/ether f0:de:f1:30:99:ba brd ff:ff:ff:ff:ff:ff
> ```
> So for example if i want to make sure that GVRP is (in)active, i have to (un)set it again.
> 

iproute2 does not use github for problem reports. Please use mailing list netdev@vger.kernel.org

To see all the options you need to use -d (show details) option.

**Comment by Harvie** [comment]
> To see all the options you need to use -d (show details) option.

@shemminger Thanks! that helpded a lot!
