### ISSUE TITLE
ip link output

### ISSUE THREAD

**Issue by gunhu** [shemminger/iproute2#22]
Hi everyone,

I wanted to point out something on `ip -s link` output:

>$ ip -s link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    RX: bytes  packets  errors  dropped overrun mcast   
    100        2        0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    100        2        0       0       0       0       
>

When I'm debugging network issues I want to have all information about a network card.

I mean all relevant timers to see if something wrong is going on without using ethtool.

Let me say that iproute2 is a great tool and I want to contribute.

ifconfig (net-tools package which is deprecated says lwn.net) was showing this kind of timer without adding extra verbose option.

>$ ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2  bytes 100 (100.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 100 (100.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
>

Is it performance related ?

If not is it possible to make a PR to remove the need to specify `-s` option twice to have this kind of timers:

>$ ip -s -s link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    RX: bytes  packets  errors  dropped overrun mcast   
    100        2        0       0       0       0       
    RX errors: length   crc     frame   fifo    missed
               0        0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    100        2        0       0       0       0       
    TX errors: aborted  fifo   window heartbeat transns
               0        0       0       0       0       
>

Thanks for your kind advice about it.

Regards,

**Comment by shemminger** [comment]
On Thu, 29 Nov 2018 08:36:06 -0800
Alexis VACHETTE <notifications@github.com> wrote:

> Hi everyone,
> 
> I wanted to point out something on `ip -s link` output:
> 
> `
> $ ip -s link
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     RX: bytes  packets  errors  dropped overrun mcast   
>     100        2        0       0       0       0       
>     TX: bytes  packets  errors  dropped carrier collsns 
>     100        2        0       0       0       0       
> 
> `
> 
> When I'm debugging network issues I want to have all information about a network card.
> 
> All relevant timers to see if something wrong is going on without using ethtool.
> 
> Let me say that iproute2 is a great tool and I want to contribute.
> 
> ifconfig (net-tools package which is deprecated) was showing this kind of timer without adding extra verbose option.
> 
> `
> $ ifconfig
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
> ------------------------------------------------------
>         RX packets 2  bytes 100 (100.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 2  bytes 100 (100.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> `
> 
> Is it performance related ?
> 
> If not is it possible to make a PR to remove the need to specify `-s` twice to have this kind of timers:
> 
> `
> $ ip -s -s link
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     RX: bytes  packets  errors  dropped overrun mcast   
>     100        2        0       0       0       0       
>     RX errors: length   crc     frame   fifo    missed
>                0        0       0       0       0       
>     TX: bytes  packets  errors  dropped carrier collsns 
>     100        2        0       0       0       0       
>     TX errors: aborted  fifo   window heartbeat transns
>                0        0       0       0       0       
> `
> 
> Thanks for your kind advice about it.
> 
> Regards,
> 

github is not used for iproute2 development. Please send all bugs/problems/patches to the
Linux network mailing list netdev@vger.kernel.org and add iproute2 somewhere in subject.

**Comment by gunhu** [comment]
Thanks I will submit the problem/patch directly on the mailing list.

Regards,
