### ISSUE TITLE
some man pages are missing

### ISSUE THREAD

**Issue by fuji246** [shemminger/iproute2#23]
looks like the man page for netem is missing, I did see that before. And looks like the GI Model in the man page is also missing.

**Comment by shemminger** [comment]
On Tue, 18 Dec 2018 16:57:49 -0800
Jiantao Fu <notifications@github.com> wrote:

> looks like the man page for netem is missing, I did see that before. And looks like the GI Model in the man page is also missing.
> 

iproute2 does not use github. Please send all requests/problems/complaints to netdev@vger.kernel.org.
Or better yet put something together and email a patch.
