### ISSUE TITLE
ip tunnel optin  ignore-df is missing

### ISSUE THREAD

**Issue by ruben-herold** [shemminger/iproute2#24]
hi,

in the mangpage the ignore-df option for gre tunnel is mentiont but I can't find it in  ip tunnel help and
it not seems to be accepted on command line:

`
ruben@work:[~/Downloads/iproute2-4.20.0/ip] > uname -a
Linux work 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux

ruben@work:[~/Downloads/iproute2-4.20.0/ip] > sudo ./ip tunnel add gre0 mode gre remote 172.168.10.25  ttl 255 ignore-df
Error: either "name" is duplicate, or "ignore-df" is a garbage.
`

**Comment by shemminger** [comment]
On Wed, 13 Mar 2019 09:07:09 +0000 (UTC)
Ruben Herold <notifications@github.com> wrote:

> hi,
> 
> in the mangpage the ignore-df option for gre tunnel is mentiont but I can't find it in  ip tunnel help and
> it not seems to be accepted on command line:
> 
> `
> ruben@work:[~/Downloads/iproute2-4.20.0/ip] > uname -a
> Linux work 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
> 
> ruben@work:[~/Downloads/iproute2-4.20.0/ip] > sudo ./ip tunnel add gre0 mode gre remote 172.168.10.25  ttl 255 ignore-df
> Error: either "name" is duplicate, or "ignore-df" is a garbage.
> `
> 
> 
> 


Ignore-df went in kernel 4.12

**Comment by ruben-herold** [comment]
Thx for the info. Did you know any alternatives? I found no way to clear the DF Bit with iptables or so.

Am 14. März 2019 01:22:09 MEZ schrieb Stephen Hemminger <notifications@github.com>:
>On Wed, 13 Mar 2019 09:07:09 +0000 (UTC)
>Ruben Herold <notifications@github.com> wrote:
>
>> hi,
>> 
>> in the mangpage the ignore-df option for gre tunnel is mentiont but I
>can't find it in  ip tunnel help and
>> it not seems to be accepted on command line:
>> 
>> `
>> ruben@work:[~/Downloads/iproute2-4.20.0/ip] > uname -a
>> Linux work 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64
>GNU/Linux
>> 
>> ruben@work:[~/Downloads/iproute2-4.20.0/ip] > sudo ./ip tunnel add
>gre0 mode gre remote 172.168.10.25  ttl 255 ignore-df
>> Error: either "name" is duplicate, or "ignore-df" is a garbage.
>> `
>> 
>> 
>> 
>
>
>Ignore-df went in kernel 4.12
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/shemminger/iproute2/issues/24#issuecomment-472656645

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
