### ISSUE TITLE
fail to build on musl-libc

### ISSUE THREAD

**Issue by dengqf6** [shemminger/iproute2#26]
https://github.com/openwrt/openwrt/pull/2068#issuecomment-493353900
```
In file included from devlink.c:25:0:
/home/dedeckeh/arm-virt-staging/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.4.0_musl_eabi/include/sys/sysinfo.h:10:8: error: redefinition of 'struct sysinfo'
struct sysinfo {
^~~~~~~
In file included from ../include/uapi/linux/kernel.h:5:0,
from ../include/uapi/linux/netlink.h:5,
from ../include/uapi/linux/genetlink.h:6,
from devlink.c:21:
../include/uapi/linux/sysinfo.h:8:8: note: originally defined here
struct sysinfo {
^~~~~~~
```

**Comment by shemminger** [comment]
On Sat, 18 May 2019 06:05:25 -0700
Deng Qingfang <notifications@github.com> wrote:

> https://github.com/openwrt/openwrt/pull/2068#issuecomment-493353900
> ```
> In file included from devlink.c:25:0:
> /home/dedeckeh/arm-virt-staging/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.4.0_musl_eabi/include/sys/sysinfo.h:10:8: error: redefinition of 'struct sysinfo'
> struct sysinfo {
> ^~~~~~~
> In file included from ../include/uapi/linux/kernel.h:5:0,
> from ../include/uapi/linux/netlink.h:5,
> from ../include/uapi/linux/genetlink.h:6,
> from devlink.c:21:
> ../include/uapi/linux/sysinfo.h:8:8: note: originally defined here
> struct sysinfo {
> ^~~~~~~
> ```
> 

Github is not the defacto upstream for iproute2
please see git://git.kernel.org/pub/scm/network/iproute2/iproute2.git
and report issues to netdev@vger.kernel.org.

Did you  try adding linux/sysinfo.h to devlink.c

**Comment by dengqf6** [comment]
Please take a look at the ref'ed PR
The error is redefintion of `struct sysinfo`. It seems that musl-libc includes `linux/sysinfo.h` somewhere else, causing this error.
The patch below is my workaround to this error, but I have not tested it on glibc or uclibc
```diff
--- a/devlink/devlink.c
+++ b/devlink/devlink.c
@@ -22,7 +22,9 @@
 #include <linux/devlink.h>
 #include <libmnl/libmnl.h>
 #include <netinet/ether.h>
+#ifdef __GLIBC__
 #include <sys/sysinfo.h>
+#endif
 #include <sys/queue.h>

 #include "SNAPSHOT.h"
```

**Comment by shemminger** [comment]
On Sat, 18 May 2019 06:59:13 -0700
Deng Qingfang <notifications@github.com> wrote:

> Please take a look at the ref'ed PR
> The error is redefintion of `struct sysinfo`. It seems that musl-libc includes `linux/sysinfo.h` somewhere else, causing this error.
> The patch below is my workaround to this error, but I have not tested it on glibc or uclibc
> ```diff
> --- a/devlink/devlink.c
> +++ b/devlink/devlink.c
> @@ -22,7 +22,9 @@
>  #include <linux/devlink.h>
>  #include <libmnl/libmnl.h>
>  #include <netinet/ether.h>
> +#ifdef __GLIBC__
>  #include <sys/sysinfo.h>
> +#endif
>  #include <sys/queue.h>
> 
>  #include "SNAPSHOT.h"
> ```
> 

Please send patches to netdev@vger.kernel.org

Adding #ifdef for GLIBC is unlikely to be accepted.
It was not necessary anywhere else.

**Comment by dengqf6** [comment]
This is what I found https://lore.kernel.org/patchwork/patch/449607/
It seems related to `kernel.h`, but the patch never got merged
