### ISSUE TITLE
Mirror does not work

### ISSUE THREAD

**Issue by Neustradamus** [shemminger/iproute2#28]
I see that it is not up-to-date, the mirror does not work, can you solve it?
- https://git.kernel.org/pub/scm/network/iproute2/iproute2.git

Thanks in advance.

**Comment by shemminger** [comment]
On Sat, 07 Dec 2019 14:08:34 -0800
Neustradamus <notifications@github.com> wrote:

> I see that it is not up-to-date, the mirror does not work, can you solve it?
> - https://git.kernel.org/pub/scm/network/iproute2/iproute2.git
> 
> Thanks in advance.
> 

Github does not offer automatic mirror service from kernel.org to github.
Updating requires manual operation, something I don't want to bother to do.

**Comment by shemminger** [comment]
I am switching to pushing on both kernel.org and github

**Comment by Neustradamus** [comment]
@shemminger: Thanks a lot! :)

**Comment by shemminger** [comment]
Discovered that git can update two remotes at once, now the base local repo
pushes to both

**Comment by Neustradamus** [comment]
@shemminger: Perfect! :)

**Comment by Neustradamus** [comment]
@shemminger: Little request, can you add a mirror of bridge-utils with same conf from here?
- https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/bridge-utils.git/

I have discovered a 1.7 in this previous link :)
-> Not in : https://mirrors.edge.kernel.org/pub/linux/utils/net/bridge-utils/
-> Not in SourceForge too (like 1.6)

SourceForge: https://sourceforge.net/projects/bridge/files/bridge/
- Rename https://sourceforge.net/projects/bridge/files/bridge/1.1/ to https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.1/
- Move https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5.tar.gz into https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5/bridge-utils-1.5.tar.gz
- Add https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.6/
- Add https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.7/

Can you see before devel ending of bridge-utils, please add to have a complete ending...

Code from Debian project?
- https://packages.debian.org/sid/bridge-utils

Have you looked code from forks?
- https://github.com/AAmamou/bridge_utils/commits/trill <-- missing code here
- https://github.com/brettsheffield/bridge-utils/commits/master <-- missing code here

After it, can you add in README:
A link to: https://wiki.linuxfoundation.org/networking/bridge
And inform people bridge-utils has been replaced by iproute2 and links...

Thanks in advance.

**Comment by shemminger** [comment]
On Tue, 14 Jul 2020 21:33:37 -0700
Neustradamus <notifications@github.com> wrote:

> @shemminger: Little request, can you add a mirror of bridge-utils with same conf from here?
> - https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/bridge-utils.git/
> 
> I have discovered a 1.7 in this previous link :)
> -> Not in : https://mirrors.edge.kernel.org/pub/linux/utils/net/bridge-utils/
> -> Not in SourceForge too (like 1.6)  
> 
> SourceForge: https://sourceforge.net/projects/bridge/files/bridge/
> - Rename https://sourceforge.net/projects/bridge/files/bridge/1.1/ to https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.1/
> - Move https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5.tar.gz into https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5/bridge-utils-1.5.tar.gz
> - Add https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.6/
> - Add https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.7/
> 
> Can you see before devel ending of bridge-utils, please add to have a complete ending...
> 
> Code from Debian project?
> - https://packages.debian.org/sid/bridge-utils
> 
> Have you looked code from forks?
> - https://github.com/AAmamou/bridge_utils/commits/trill <-- missing code here
> - https://github.com/brettsheffield/bridge-utils/commits/master <-- missing code here
> 
> After it, can you add in README:
> A link to: https://wiki.linuxfoundation.org/networking/bridge
> And inform people bridge-utils has been replaced by iproute2 and links...
> 
> Thanks in advance.
> 

Source forge is dead and will not be updated.
The repo is going to be removed in next month or so.

Kernel.org location will go back to:
https://mirrors.edge.kernel.org/pub/linux/utils/net/bridge-utils/
And will be mirrored to github

Trill never made it and is dead.
Bridge-utils is on legacy support only. No changes expected, no new features ever.

**Comment by Neustradamus** [comment]
@shemminger: Can you add the mirror of bridge-utils?

And I have seen problems: a 1.7 (very old date) and a master + main branches.
- https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/bridge-utils/
- 3 years, 7 months ago: https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/bridge-utils/+/refs/tags/v1.7
- https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/bridge-utils/+/refs/heads/main
- https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/bridge-utils/+/refs/heads/master

And for security reason, it will be nice.

Thanks in advance.

**Comment by Neustradamus** [comment]
1.7 is not here:
- https://mirrors.edge.kernel.org/pub/linux/utils/net/bridge-utils/
