### ISSUE TITLE
peer_notify_dealy parameters  is Iincorrect parameter name

### ISSUE THREAD

**Issue by qwangli** [shemminger/iproute2#30]
parameters and kernel parameters are named indefinitely, and the kernel parameter is peer_notif_delay
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/bonding?h=v4.19.86&id=2a458eddc4c270a435c26f0d22c46da36cbf00d2

**Comment by qwangli** [comment]
version < 5.5

**Comment by qwangli** [comment]
version < 5.5

**Comment by shemminger** [comment]
You are talking into a vacuum.
Iproute2 does not use github. This is a static mirror.
