### ISSUE TITLE
ip rule for GRE tunnel

### ISSUE THREAD

**Issue by liranodiz** [shemminger/iproute2#34]
Is it possible to set  IP rule for GRE tunnel? in the IP rule man there is missing information about the "tun_id" selector parameter, what is the meaning of this parameter? 
How can i set IP rule for the following GRE tunnel?

`[root@localhost ~]# ip tunnel show
gre0: gre/ip remote any local any ttl inherit nopmtudisc
tunl0: any/ip remote any local any ttl inherit nopmtudisc
sit0: ipv6/ip remote any local any ttl 64 nopmtudisc
greT1: gre/ip remote 70.70.70.2 local 70.70.70.1 ttl inherit key 1
ip_vti0: ip/ip remote any local any ttl inherit nopmtudisc key 0
`

**Comment by shemminger** [comment]
On Mon, 12 Oct 2020 07:06:01 -0700
liranodiz <notifications@github.com> wrote:

> Is it possible to set  IP rule for GRE tunnel? in the IP rule man there is missing information about the "tun_id" selector parameter, what is the meaning of this parameter? 
> How can is set IP rule for the following GRE tunnel?
> 
> `[root@localhost ~]# ip tunnel show
> gre0: gre/ip remote any local any ttl inherit nopmtudisc
> tunl0: any/ip remote any local any ttl inherit nopmtudisc
> sit0: ipv6/ip remote any local any ttl 64 nopmtudisc
> greT1: gre/ip remote 70.70.70.2 local 70.70.70.1 ttl inherit key 1
> ip_vti0: ip/ip remote any local any ttl inherit nopmtudisc key 0
> `
> 

Iproute2 does not use github project infrastructure.
Please send all questions and pull requests to netdev@vger.kernel.org

**Comment by shemminger** [comment]
Iproute2 uses netdev@vger.kernel.org for development not github.
