### ISSUE TITLE
can ip link show bond slaves in json format

### ISSUE THREAD

**Issue by RiccardoManfrin** [shemminger/iproute2#35]
I could not find a proper way to infer the slave interfaces that are usually found under 

`/sys/class/net/<ifname>/bonding/slaves`

Is there a way to check them?

**Comment by shemminger** [comment]
On Fri, 13 Nov 2020 00:47:59 -0800
Riccardo Manfrin <notifications@github.com> wrote:

> I could not find a proper way to infer the slave interfaces that are usually found under 
> 
> `/sys/class/net/<ifname>/bonding/slaves`
> 
> Is there a way to check them?
> 
> 

The master device is listed on each slave interface in ip link.
This gets the information but is upside downn

**Comment by RiccardoManfrin** [comment]
I see.. bit of unfortunate. Thanks
