### ISSUE TITLE
[bug] 5.9 release reporting itself as 5.8

### ISSUE THREAD

**Issue by n8v8R** [shemminger/iproute2#36]
```
# tc -V
tc utility, iproute2-5.8.0
# ip -V
ip utility, iproute2-5.8.0
# ss -V
ss utility, iproute2-5.8.0
# devlink -V
devlink utility, iproute2-5.8.0
# genl -V
genl utility, iproute2-5.8.0
```

looking at 

https://github.com/shemminger/iproute2/blob/v5.9.0/include/version.h#L1

it seems that the version number not been bumped with the release. This could be confusing in a debugging scenario when reporting the utility version.

and for some reason bridge version reporting does not seem to work at all.

```
# bridge -V
bridge utility, 0.0
```

**Comment by shemminger** [comment]
Thanks the step in the script for generating release were backwards... It was tagging then generating version.h

Bridge utility also fixed

**Comment by shemminger** [comment]
1. iproute2-release script (not in tree) fixed
