### ISSUE TITLE
No Makefile in the `doc` directory, even though the README mentions it.

### ISSUE THREAD

**Issue by lockywolf** [shemminger/iproute2#39]
The readme says: 
`
3. To make documentation, cd to doc/ directory , then
   look at start of Makefile and set correct values for
   PAGESIZE=a4		, ie: a4 , letter ...	(string)
   PAGESPERPAGE=2	, ie: 1 , 2 ...		(numeric)
   and make there. It assumes, that latex, dvips and psnup
   are in your path.
`

But there is no Makefile in `doc`. (In fact, there seems to be not too much documentation either.)

**Comment by shemminger** [comment]
Iproute2 uses netdev@vger.kernel.org for development not github.
