### ISSUE TITLE
How to set the noudpcsum flag when create a vxlan device with external argument set ?

### ISSUE THREAD

**Issue by alpha-li** [shemminger/iproute2#40]
When I create a vxlan device with such command:
`$ ip link add vxl1 type vxlan id 1001 noudpcsum remote 10.0.0.1 `
then the created vxlan device has noudpcsum flag:
`$ ip -d link show vxl1`
7: vxl1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 7a:0e:8a:de:a7:ef brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 
    vxlan id 1001 remote 10.0.0.1 srcport 0 0 dstport 8472 ttl auto ageing 300 noudpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 

However, when I create a vxlan device with external argument:
`$ ip link add vxl2 type vxlan   noudpcsum external`
the created vxlan device detail is different from previous:
`$ ip -d link show vxl2`
8: vxl2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8e:ec:61:86:3a:7c brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 
    vxlan external addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 

So, what can I do if I am going to create a vxlan device with noudpcsum set when external argument is used?

**Comment by shemminger** [comment]
This is not the correct place to report problems.
Iproute2 uses the upstream kernel process.
Please report all questions, bugs, gripes to netdev@vger.kernel.org
