### ISSUE TITLE
5.9 versions has invalid JSON output for ERSPAN version 2

### ISSUE THREAD

**Issue by c-po** [shemminger/iproute2#41]
Hi @shemminger,

I hope this is the proper way of filing am issue I discovered using iproute2.

While working on ERSPAN support in VyOS I noticed that when reading in the JSON output into the Python JSON library there is a key with no value attached.

```bash
cpo@LR1.wue3# ip -d link show tun1070
74: tun1070@NONE: <BROADCAST,MULTICAST> mtu 1418 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 22:8c:a4:e5:98:27 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 0
    ip6erspan remote 2001:db8::ffff local 2001:db8::1 hoplimit inherit encaplimit 4 tclass inherit flowlabel 0x00000 ikey 0.0.0.77 okey 0.0.0.77 iseq oseq erspan_ver 2 erspan_dir ingress erspan_hwid 0 addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
[edit]

cpo@LR1.wue3# ip -d -j link show tun1070
[{"ifindex":74,"link":null,"ifname":"tun1070","flags":["BROADCAST","MULTICAST"],"mtu":1418,"qdisc":"noop","operstate":"DOWN","linkmode":"DEFAULT","group":"default","txqlen":1000,"link_type":"ether","address":"22:8c:a4:e5:98:27","broadcast":"ff:ff:ff:ff:ff:ff","promiscuity":0,"min_mtu":68,"max_mtu":0,"linkinfo":{"info_kind":"ip6erspan","info_data":{"remote":"2001:db8::ffff","local":"2001:db8::1","ttl":0,"encap_limit":4,"ip6_tnl_f_use_orig_tclass":true,"flowlabel":"0x00000","ikey":"0.0.0.77","okey":"0.0.0.77","iseq":true,"oseq":true,"erspan_ver":2,"erspan_dir":"erspan_hwid":"0"}},"inet6_addr_gen_mode":"none","num_tx_queues":1,"num_rx_queues":1,"gso_max_size":65536,"gso_max_segs":65535}]
```

The problem is that `ip -d link show tun1070` shows:  `erspan_dir ingress` but the corresponding JSON key has no value: `"erspan_dir":`

My expectation would be to see: `"erspan_dir":"ingres"`.

```
cpo@LR1.wue3# /usr/sbin/ip -V
ip utility, iproute2-5.9.0
```

For an unknon reason (not realted to this problem) the Debian version flags it with a different version number.
```
cpo@LR1.wue3# dpkg -l | grep iproute2
ii  iproute2                             5.10.0-4~bpo10+1                    amd64        networking and traffic control tools
```

Issue is also present in `iproute2-ss191125`

**Comment by shemminger** [comment]
On Mon, 05 Apr 2021 13:28:42 -0700
Christian Poessinger ***@***.***> wrote:

> Hi @shemminger,
> 
> I hope this is the proper way of filing a bug in iproute2.

It is not. Please post to ***@***.***

Also 5.9 is old, current version is 5.11

**Comment by c-po** [comment]
Submitted fix in addition to your first version https://lore.kernel.org/netdev/20210409104947.36827-1-christian@poessinger.com/T/#u
