### ISSUE TITLE
ip addr is hard to read with no new lines in between outputs.

### ISSUE THREAD

**Issue by BlackTango** [shemminger/iproute2#42]
Here is the normal output for the command ip addr:
![image](https://user-images.githubusercontent.com/15683321/116340221-cd915780-a7ac-11eb-85b1-f51d34193542.png)

Here is the normal output for the command ifconfig:
![image](https://user-images.githubusercontent.com/15683321/116340275-e568db80-a7ac-11eb-838e-16ec8d433c0f.png)

ip addr just need a new line between outputs so its easier to read.
I would have added it myself but im too noob.

**Comment by shemminger** [comment]
Thank you for your idea, but changing output format like that might break existing users. There are applications that script the output. Have you tried the brief and color output format:
 $ ip -br -c addr

PS: github issues are not used for this utility, see the README.

**Comment by BlackTango** [comment]
Understood.
I'm sorry about that, wont happen again.
