### ISSUE TITLE
Referring to interfaces by index using "if%u" is not documented.

### ISSUE THREAD

**Issue by socketpair** [shemminger/iproute2#44]
So `ip addr add if%5 1.2.3.4/24` works. I want to use the feature in my project, but absence of this way stops me from it. So, should it be documented and also added to help messages ? If yes, I can make a patch. I just want to understand if it is a stable feature or not.

**Comment by shemminger** [comment]
iproute is not developed using github. Please send all changes to netdev@vger.kernel.org
