### ISSUE TITLE
"ip addr show" returning device names that won't work with "ip addr show dev"

### ISSUE THREAD

**Issue by MrPippin66** [shemminger/iproute2#45]
Version: iproute-4.11.0-25.el7_7.2.x86_64

# ip -V
ip utility, iproute2-ss170501

Issue: If I run "ip -br addr show" on a server with network vlans, I get addresses like below:

# ip -br addr show
lo               UNKNOWN        127.0.0.1/8
eno1             DOWN
eno2             DOWN
eno3             DOWN
eno4             DOWN
ens3f0           UP             10.2.13.3/24
ens2f0           UP
ens3f1           UP             10.2.14.3/24
ens2f1           UP
bond0            UP
bond0.2176@bond0 UP             10.170.176.33/23
enp0s20f0u1u6    DOWN

However, if I attempt to get details for the vlan device (bond0.2176@bond0 in this case), as returned from "ip -br addr show", I get an error saying the device is invalid.

Example:

# ip addr show dev bond0.2176@bond0
Device "bond0.2176@bond0" does not exist.

But, if I run the same command with just "bond0.2176', it works.

Example:

# ip addr show dev bond0.2176
12: bond0.2176@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:10:9b:67:18:60 brd ff:ff:ff:ff:ff:ff
    inet 10.170.176.33/23 brd 10.170.177.255 scope global bond0.2176
       valid_lft forever preferred_lft forever

Why is "ip addr show" returning device names that won't work with "ip addr show dev"?

**Comment by shemminger** [comment]
The iproute2 project does not use github as main development process.
To answer your question the part after the @ is the portion of the network interface that is list as the "link" or master device in the bonding case.
