### ISSUE TITLE
[New Proposal] ss - Grab socket information across network namespace

### ISSUE THREAD

**Issue by yinlonglyl** [shemminger/iproute2#46]
Dear iproute developers:

Currently ss only grab socket information in its own network namespace, it is inconvenient when debugging network issues in cloud native environment(e.g. k8s). 
So do you think it's appropriate to add an option to dump socket info in all(or specified process) namespaces? 
I've done this in my develop env, it makes easier to monitor container's network.

Thanks!

**Comment by shemminger** [comment]
On Tue, 22 Jun 2021 05:31:42 -0700
yinlonglyl ***@***.***> wrote:

> Dear iproute developers:
> 
> Currently ss only grab socket information in its own network namespace, it is inconvenient when debugging network issues in cloud native environment(e.g. k8s). 
> So do you think it's appropriate to add an option to dump socket info in all(or specified process) namespaces? 
> I've done this in my develop env, it makes easier to monitor container's network.
> 

Please put discussion on ***@***.***
For iproute2 github is a mirror only.

**Comment by shemminger** [comment]
Discussion is on netdev mailing list.
iproute2 on github is not used for disucssions.
