### ISSUE TITLE
tc-load-bpf-fail-Log buffer too small to dump verifier log 16777215 bytes (9 tries)!

### ISSUE THREAD

**Issue by zf1575192187** [shemminger/iproute2#48]
tc's code is enabled log by default. Due to the increase in the number of instructions, resulting in "Log buffer too small to dump verifier log 16777215 bytes (9 tries)!"

bpf_log_realloc
if (!ctx->log) {
log_size = 65536;
} else if (log_size < log_max) {
log_size <<= 1;
if (log_size > log_max)
	log_size = log_max;
} else {
return -EINVAL;
}

Therefore, I would like to ask if consider setting the log according to the verbose

**Comment by shemminger** [comment]
Please post to ***@***.***
