### ISSUE TITLE
How to make ss?

### ISSUE THREAD

**Issue by linrl3** [shemminger/iproute2#49]
In ./iproute2/misc, I run `make ss`, but got:
```
Makefile:7: ../config.mk: No such file or directory
make: *** No rule to make target '../config.mk'.  Stop.
```
Where is config.mk?

**Comment by shemminger** [comment]
Only make at top level is supposed to be used.
The config.mk is generated by the configure she'll script.

I am replying here out of convenience only. This project uses netdev@vger.kernel.org for all patches, bug report, and questions. GitHub is a read only mirror.

**Comment by linrl3** [comment]
@shemminger Got it. Thank you for your reply!
