### ISSUE TITLE
oneline -o mode on "ip xfrm monitor" isn't

### ISSUE THREAD

**Issue by pprindeville** [shemminger/iproute2#5]
Just ran "ip -o xfrm monitor" and saw:

```
src 0.0.0.0/0 dst 0.0.0.0/0 \	dir out priority 2051 ptype main \	mark -1879048191/0xffffffff
	tmpl src 203.0.130.10 dst 198.51.130.30\		proto esp reqid 16384 mode tunnel\
```

clearly there's a newline after the "mark" info and this is 2 lines, not one.  The problem seems to come from here:

```
void xfrm_xfrma_print(struct rtattr *tb[], __u16 family,
        FILE *fp, const char *prefix)
{
        if (tb[XFRMA_MARK]) {
                struct rtattr *rta = tb[XFRMA_MARK];
                struct xfrm_mark *m = (struct xfrm_mark *) RTA_DATA(rta);
                fprintf(fp, "\tmark %d/0x%x\n", m->v, m->m);
        }
```

Looks like that should be:

```
fprintf(fp, "\tmark %d/0x%x%s", m->v, m->m, _SL_);
```

instead.

**Comment by pprindeville** [comment]
Other comment: it's not clear why the mark (which is a __u32) is being displayed as %d.  At a minimum, it should be unsigned (%u) or preferably in hex (%x) to match the mask.

**Comment by shemminger** [comment]
You are shouting into the wind, this project is not rooted on github.

**Comment by pprindeville** [comment]
Yeah, that was months ago.  Maybe retitle the repo, or put a notice in the README?

**Comment by jadjay** [comment]
K' didn't notice that

Happy new year btw,


*Jérôme Avond*
m/j : jerome.avond@alolise.org
