### ISSUE TITLE
IPv6 link-local gateway is not allowed

### ISSUE THREAD

**Issue by runapp** [shemminger/iproute2#51]
When I run `ip -6 route add default via fe80::1122 dev eth0`, I got `Gateway can not be a local address.`, while the gateway works flawlessly on Windows. Any chance to add it?

**Comment by shemminger** [comment]
On Mon, 16 Aug 2021 09:17:22 -0700
runapp ***@***.***> wrote:

> When I run `ip -6 route add default via fe80::1122 dev eth0`, I got `Gateway can not be a local address.`, while the gateway works flawlessly on Windows. Any chance to add it?


This looks like a kernel not a utility issue.

iproute2 does not use github for development (this is pure read-only mirror).
Send all questions/problems to ***@***.*** mailing list.

**Comment by shemminger** [comment]
iproute2 does not use github for development (this is pure read-only mirror).

**Comment by runapp** [comment]
I see. I'll dig it further.
PS. would you add the read-only-mirror tip in repo description or README? I think that will make it easy for some people to find the right place to discuss about `iproute2`.
