### ISSUE TITLE
ip route oif is not forward blocked

### ISSUE THREAD

**Issue by egberts** [shemminger/iproute2#54]
when a netdev IPv4 interface is sysctl-configured as `net.ipv4.conf.eth0.forwarding=0` (IP forwarding disabled on `eth0`), the command:

    ip -o route get 8.8.8.8 oif eth0

was expecting "no route found" or something.

Did I assumed too much or is this a feature?

this is a single Ethernet PC running Linux Debian 11 (bulleyes) Linux 5.4

ip 5.10.0-4

**Comment by shemminger** [comment]
iproute2 does not use github for issues. Also iproute2 is just a CLI for the Linux kernel, the kernel is accepting your route request.  Closing this, if you want to pursue it mail to netdev@vger.kernel.org where Linux networking is maintained.

**Comment by egberts** [comment]
tried to post on netdev@vger.kernel.org but Apple Mail on iPhone doesnt send without HTML subpart therefore it gets rejected.
