### ISSUE TITLE
tc qdisc with delay strategy cause packet drop while high qps

### ISSUE THREAD

**Issue by bigbang009** [shemminger/iproute2#56]
I set tc qdisc with delay stragegy, and using http request pressure test, there is no packet loss when the qps is low, but there is packet loss when the qps is high。

the tc statement like this.
tc qdisc add dev eth0 root handle 1: prio bands 4
tc qdisc add dev eth0 parent 1:4 handle 40: netem delay 1000ms 0ms
tc filter add dev eth0 parent 1: prio 4 protocol ip u32 match ip dst 172.2.1.2 flowid 1:4

while the request qps is high, such as 600. the qdisc will drop the package.
![850463ba72dde17ea238b1172c14c9294905712c](https://user-images.githubusercontent.com/36918717/146182255-581903d3-6c79-42f6-a271-8d5e7018371a.png)

Is there have a performance issue with tc qdisc?

**Comment by shemminger** [comment]
Github is not normally used for Linux kernel issues.


Internally netem keeps a queue of packets to send. If it is delaying then you need have a queue big enough to hold the maximum number of packets over that interval.  With your example the limit is 1000 packets so if you go over 1000 packets/sec then packets will get dropped.  Set limit to a larger value like a 100,000 packets?
