### ISSUE TITLE
setns is _GNU_SOURCE?

### ISSUE THREAD

**Issue by mirschkyn** [shemminger/iproute2#57]
iproute2 wouldn't detect setns (target glibc 2.33, gcc 11.2, "cross" x86_64 ->x86_64):
...
libc has setns: no
...
Which resulted in a compile failure:
In file included from exec.c:8:
../include/namespace.h:41:19: error: static declaration of 'setns' follows non-static declaration
   41 | static inline int setns(int fd, int nstype)
      |                   ^~~~~
In file included from <snip>/usr/include/sched.h:43,

diff -urN iproute2-5.14.0.orig/configure iproute2-5.14.0/configure
--- iproute2-5.14.0.orig/configure	2021-12-22 10:45:19.106892954 +0100
+++ iproute2-5.14.0/configure	2021-12-22 10:45:39.267338975 +0100
@@ -180,6 +180,7 @@
 check_setns()
 {
     cat >$TMPDIR/setnstest.c <<EOF
+#define _GNU_SOURCE
 #include <sched.h>
 int main(int argc, char **argv)
 {

Fixes detection and building for me.

**Comment by mirschkyn** [comment]
Which wasn't really the issue, but still.

**Comment by shemminger** [comment]
iproute2 does not use github for issue tracking.

Not sure what distro you are using, but the existing configure works on Debian and Redhat.
