### ISSUE TITLE
Missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [shemminger/iproute2#58]
`fclose(fp);` should be put before Line 112.
https://github.com/shemminger/iproute2/blob/9f366536edb5158343152604e82b968be46dbf26/testsuite/tools/generate_nlmsg.c#L105-L115

**Comment by shemminger** [comment]
iproute2 does not use github to track issues or manage patches this is a read-only mirror.
There is no point in adding fclose because program will just exit anyway.
