### ISSUE TITLE
'ip -4 neigh flush all' clears extern_learn PERMANENT entries

### ISSUE THREAD

**Issue by obaidamin** [shemminger/iproute2#61]
Hello all, 
Reporting an issue for the first time. If this is not the right place to file a bug then please point me to the one. 

We recently noticed the following behavior of the flush command. 
```
# ip -4 neigh show
192.168.1.2 dev eth0 lladdr 00:01:e8:8b:44:71 REACHABLE
2.2.2.2 dev Vlan100 lladdr 00:11:01:01:01:01 extern_learn  PERMANENT

# ip -4 neigh flush all 
# ip -4 neigh show
192.168.1.2 dev eth0 lladdr 00:01:e8:8b:44:71 REACHABLE
```
The `ip -4 neigh flush all` command flushed the PERMANENT entry as well, which is wrong according to the man page (https://man7.org/linux/man-pages/man8/ip-neighbour.8.html). The issue was only observed with PERMANENT ARP entries created using extern_learn flag.  Other type of PERMANENT entries remain in the ARP table as shown below.  

```
# ip -4 neigh flush all 
192.168.1.2 dev eth0 lladdr 00:01:e8:8b:44:71 REACHABLE
2.3.2.2 dev Vlan100 lladdr 00:12:01:01:01:01 PERMANENT

# ip -4 neigh flush all 

# ip -4 neigh show
192.168.1.2 dev eth0 lladdr 00:01:e8:8b:44:71 REACHABLE
2.3.2.2 dev Vlan100 lladdr 00:12:01:01:01:01 PERMANENT
```

Version in use:
```
# ip -V
ip utility, iproute2-ss190107
```

**Comment by shemminger** [comment]
Iproute2 does not use github for development, please forward all issues to netdev@vger.kernel.org

That version of iproute2 is from 2019 and is out of date.
