### ISSUE TITLE
drop_cap() stops ip from working with capabilities

### ISSUE THREAD

**Issue by tinkerator** [shemminger/iproute2#62]
I noticed the following while looking into this question:

- https://stackoverflow.com/questions/72015197/allow-non-root-user-of-container-to-execute-binaries-that-need-capabilities

The `lib/utils.c` code contains some complicated code that it appears is trying to prevent Ambient capabilities from being inherited except in specific cases (`ip/ip.c:main()` calls `drop_cap()` except in the `ip vrf exec` case.). The code clears _all capabilities_ in order to prevent Ambient capabilities from being available. The following change achieves this much more precisely. It also permits `ip` to not need to be setuid-root or executed under `sudo` since it can be empowered by file capabilities:
```
diff --git a/lib/utils.c b/lib/utils.c
index 53d31006..681e4aee 100644
--- a/lib/utils.c
+++ b/lib/utils.c
@@ -1555,25 +1555,10 @@ void drop_cap(void)
 #ifdef HAVE_LIBCAP
        /* don't harmstring root/sudo */
        if (getuid() != 0 && geteuid() != 0) {
-               cap_t capabilities;
-               cap_value_t net_admin = CAP_NET_ADMIN;
-               cap_flag_t inheritable = CAP_INHERITABLE;
-               cap_flag_value_t is_set;
-
-               capabilities = cap_get_proc();
-               if (!capabilities)
-                       exit(EXIT_FAILURE);
-               if (cap_get_flag(capabilities, net_admin, inheritable,
-                   &is_set) != 0)
+               /* prevent any ambient capabilities from being inheritable */
+               if (cap_reset_ambient() != 0) {
                        exit(EXIT_FAILURE);
-               /* apps with ambient caps can fork and call ip */
-               if (is_set == CAP_CLEAR) {
-                       if (cap_clear(capabilities) != 0)
-                               exit(EXIT_FAILURE);
-                       if (cap_set_proc(capabilities) != 0)
-                               exit(EXIT_FAILURE);
                }
-               cap_free(capabilities);
        }
 #endif
 }
```

**Comment by tinkerator** [comment]
I also found a bug in the `libcap` man page for `cap_reset_ambient()` and reported that here: https://bugzilla.kernel.org/show_bug.cgi?id=215910 . Perhaps the docs made this approach seem harder?

**Comment by shemminger** [comment]
iproute2 does not use github for its workflow. This a pure read-only mirror.
Please raise your issue on netdev@vger.kernel.org.
Also use git blame to find original author and cc: that person on the email

**Comment by tinkerator** [comment]
Done:

https://lore.kernel.org/netdev/CABCx3R0QbN2anNX5mO1iPGZNgS=wdWr+Rb=bYGwf24o6jxjnaQ@mail.gmail.com/
